name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: docker login
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
              
    - uses: actions/checkout@v3
    - name: push into docker hub
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sa-auth-service:latest
